<?php
/**
 * @file
 *
 * Integrates with Recurly to provide hosted links for Drupal user accounts.
 *
 * Enabling this module is not recommended if your site is using Commerce
 * Recurly or other modules that provide local management of Recurly accounts.
 */

/**
 * Implements hook_menu().
 */
function recurly_hosted_menu() {
  $items = array();

  // Configure built-in pages if enabled.
  $entity_type = variable_get('recurly_entity_type', 'user');
  if ($entity_type && variable_get('recurly_pages', '1')) {
    $entity_path = $entity_type . '/%' . $entity_type;
    $items[$entity_path . '/subscription/billing'] = array(
      'title' => 'Update billing information',
      'page callback' => 'recurly_hosted_account_redirect',
      'page arguments' => array($entity_type, 1),
      'access callback' => 'recurly_subscription_page_access',
      'access arguments' => array($entity_type, 1, 'update_billing'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
    );
  }

  return $items;
}

/**
 * Implements hook_recurly_url_info().
 */
function recurly_hosted_recurly_url_info($operation, $context) {
  switch ($operation) {
    case 'update_billing':
      return recurly_hosted_account_manage_url($context['account'], TRUE);
    case 'subscribe':
      $entity = $context['entity'];
      $entity_type = $context['entity_type'];
			$id = recurly_extract_id($entity_type, $entity);
		  $account_code = $entity_type . '-' . $id;
      $username = recurly_entity_label($entity_type, $entity);
      return recurly_hosted_subscription_plan_purchase_url($context['plan_code'], $account_code, $username);
  }
}

/**
 * Menu callback; Redirect an entity to Recurly.com for management.
 *
 * Note that because this function logs the user into the Recurly front-end
 * interface without a password, it should only be called if the user has
 * already passed the recurly_subscription_page_access() check.
 */
function recurly_hosted_account_redirect($entity_type, $entity) {
  global $user;
  $id = recurly_extract_id($entity_type, $entity);
  $recurly_account = recurly_account_load(array('entity_type' => $entity_type, 'entity_id' => $id));
  if ($recurly_account) {
    drupal_goto(recurly_hosted_account_manage_url($recurly_account, TRUE));
  }
  else {
    return MENU_NOT_FOUND;
  }
}

/**
 * Implements hook_user().
 */
function recurly_hosted_user($type, $edit, &$account, $category = NULL) {
  if ($type == 'view') {
    return recurly_hosted_user_view($account, NULL, NULL);
  }
}

/**
 * Implements hook_user_view().
 *
 * If enabled, adds Recurly account information and management links to user
 * profiles linked to accounts.
 */
function recurly_hosted_user_view($account, $view_mode, $langcode) {
  global $user;

  // If account display on user profiles is enabled, this is an authenticated
  // account, and the current user has access to view its account information...
  if ($account->uid && _recurly_user_access('view', $account)) {
    // Initialize the Recurly client.
    recurly_client_initialize();

    // If the account is linked to a Recurly account...
    if ($recurly_account = recurly_account_load(array('uid' => $account->uid))) {
      // Add it to the content array.
      $account->content['recurly_account'] = array(
        '#type' => 'user_profile_category',
        '#title' => t('Subscription information'),
        '#weight' => 0,
      );

      // Build an account holder string based on available data.
      if (empty($recurly_account->company_name)) {
        $account_holder = t('@first_name @last_name', array('@first_name' => $recurly_account->first_name, '@last_name' => $recurly_account->last_name));
      }
      else {
        $account_holder = t('@first_name @last_name, @company_name', array('@first_name' => $recurly_account->first_name, '@last_name' => $recurly_account->last_name, '@company_name' => $recurly_account->company_name));
      }

      $account->content['recurly_account']['account_holder'] = array(
        '#type' => 'user_profile_item',
        '#title' => t('Account holder'),
        '#markup' => $account_holder,
      );

      // Add the account e-mail address if available.
      if (!empty($recurly_account->email)) {
        $account->content['recurly_account']['account_email'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Account e-mail address'),
          '#markup' => check_plain($recurly_account->email),
        );
      }

      // Tell the user if the account is closed.
      if ((empty($recurly_account->state) && $recurly_account->status == 'closed') ||
        (!empty($recurly_account->state) && $recurly_account->state == 'closed')) {
        $account->content['recurly_account']['account_closed'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Account status'),
          '#markup' => t('Our records indicate your account is closed. We are not currently billing your for any subscriptions.'),
        );
      }

      // Add an appropriate account edit link if the user has access.
      if (recurly_account_access('edit', $account)) {
        // Give administrators a link to the back end.
        if (user_access('administer recurly') || user_access('edit all recurly accounts')) {
          $account->content['recurly_account']['edit_account_link'] = array(
            '#type' => 'user_profile_item',
            '#title' => t('Administer account'),
            '#markup' => l(t('Edit this account at Recurly.'), recurly_hosted_account_edit_url($recurly_account)),
          );
        }

        // If Hosted Payment Pages are enabled, give users a link to their own
        // account management page if their account is active.
        if ($user->uid == $account->uid && $recurly_account->state == 'active') {
          // Give users manage links for their own accounts.
          $account->content['recurly_account']['manage_account_link'] = array(
            '#type' => 'user_profile_item',
            '#title' => t('Manage account'),
            '#markup' => l(t('Update your subscription and billing information at Recurly.'), recurly_hosted_account_manage_url($recurly_account, user_access('edit own recurly account without login'))),          );
        }
      }
    }
  }
}

/**
 * Returns an edit URL for a Recurly account.
 *
 * @param $recurly_account
 *   The recurly account values array returned by recurly_account_load.
 *
 * @return
 *   The URL for the plan's edit page at Recurly.
 */
function recurly_hosted_account_edit_url($recurly_account) {
  return recurly_hosted_url('accounts/' . $recurly_account->account_code);
}

/**
 * Returns a front end management URL for a Recurly account.
 *
 * @param $recurly_account
 *   The recurly account values array returned by recurly_account_load.
 * @param $hosted_login_token
 *   Boolean indicating whether or not to use the hosted login token in the URL
 *   if it's available in the account object; defaults to FALSE.
 *
 * @return
 *   The URL for the account's front end management page at Recurly; uses the
 *   hosted login token if specified and it's available.
 */
function recurly_hosted_account_manage_url($recurly_account, $hosted_login_token = FALSE) {
  // Return a URL using the hosted login token if available.
  if ($hosted_login_token && !empty($recurly_account->hosted_login_token)) {
    return recurly_hosted_url('account/' . $recurly_account->hosted_login_token);
  }

  return recurly_hosted_url('account');
}

/**
 * Returns a Hosted Payment Page URL for the given subscription plan.
 *
 * @param $plan
 *   The subscription plan object returned by the Recurly client.
 * @param $account_code
 *   Optional. The account code to assign to this new subscriber. This unique
 *   identifier is permanent and is used to bind the account to Drupal IDs.
 * @param $username
 *   Optional. The username that will be stored at Recurly for this subscriber.
 *   Usually just used for reference.
 * @param $settings
 *   An optional array of settings used to pre-populate the payment form.
 *   - first_name: the customer's first name
 *   - last_name: the customer's last name
 *   - email: the customer's e-mail address
 *
 * @return
 *   The URL for the plan's Hosted Payment Page at Recurly.
 */
function recurly_hosted_subscription_plan_purchase_url($plan_code, $account_code = NULL, $username = NULL, $settings = NULL) {
  $url = 'subscribe/' . $plan_code;
  if ($account_code) {
    $url .= '/' . $account_code;
    if ($username) {
      $url .= '/' . $username;
    }
  }

  if (!empty($settings)) {
    $url .= '?' . recurly_hosted_http_build_query($settings);
  }

  return recurly_hosted_url($url);
}

// copy of D7's drupal_http_build_query();
function recurly_hosted_http_build_query(array $query, $parent = '') {
  $params = array();

  foreach ($query as $key => $value) {
    $key = ($parent ? $parent . '[' . rawurlencode($key) . ']' : rawurlencode($key));

    // Recurse into children.
    if (is_array($value)) {
      $params[] = drupal_http_build_query($value, $key);
    }
    // If a query parameter value is NULL, only append its key.
    elseif (!isset($value)) {
      $params[] = $key;
    }
    else {
      // For better readability of paths in query strings, we decode slashes.
      $params[] = $key . '=' . str_replace('%2F', '/', rawurlencode($value));
    }
  }

  return implode('&', $params);
}


/**
 * Returns a form with a submit button that redirects the user to the Hosted
 * Payment Page for the given plan.
 *
 * @param $plan
 *   A subscription plan object that contains at least a valid plan code.
 */
function recurly_hosted_subscription_plan_purchase_redirect_form(&$form_state, $plan) {
  $form['plan'] = array(
    '#type' => 'value',
    '#value' => $plan,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Subscribe'),
  );

  return $form;
}

/**
 * Submit callback: redirect the user to the specified Hosted Payment Page.
 */
function recurly_hosted_subscription_plan_purchase_redirect_form_submit($form, &$form_state) {
  $form_state['redirect'] = recurly_hosted_subscription_plan_purchase_url($form_state['values']['plan']);
}
